"""PMX-specific parsing contracts and diagnostics."""

from pypmxvmd.common.pmx.cursor import PmxByteSpan, PmxCursor
from pypmxvmd.common.pmx.document import BinaryPatch, BinarySpan, FieldPath, PmxDocument
from pypmxvmd.common.pmx.errors import (
    IncompletePmxError,
    IncompletePmxWriterError,
    PmxAssemblyError,
    PmxBoneEditError,
    PmxCapabilityError,
    PmxComparisonError,
    PmxError,
    PmxFaceEditError,
    PmxFormatError,
    PmxFrameEditError,
    PmxInspectionError,
    PmxJointEditError,
    PmxMaterialEditError,
    PmxMorphEditError,
    PmxPatchError,
    PmxPlanError,
    PmxPlanStaleError,
    PmxQueryError,
    PmxRigidBodyEditError,
    PmxTransactionError,
    PmxValidationError,
    PmxVertexEditError,
    PmxWorkspaceError,
    UnsupportedPmxFeatureError,
)
from pypmxvmd.common.pmx.limits import DEFAULT_PMX_LIMITS, PmxLimits
from pypmxvmd.common.pmx.report import (
    PMX_20_REQUIRED_SECTIONS,
    PMX_21_REQUIRED_SECTIONS,
    PmxParseReport,
    PmxParseResult,
    PmxSectionReport,
)
from pypmxvmd.common.pmx.types import (
    JointType,
    MorphMaterialOperation,
    MorphPanel,
    MorphType,
    PmxIndexSize,
    PmxTextEncoding,
    RigidBodyPhysMode,
    RigidBodyShape,
    SoftBodyAeroModel,
    SoftBodyFlags,
    SoftBodyShape,
    SphMode,
    ToonSharing,
    WeightMode,
)
from pypmxvmd.common.pmx.validator import PmxValidator, validate_pmx_model
from pypmxvmd.common.pmx.writer import PmxIndexLayout, PmxWriter

__all__ = [
    "IncompletePmxError",
    "IncompletePmxWriterError",
    "PmxError",
    "PmxBoneEditError",
    "PmxAssemblyError",
    "PmxCapabilityError",
    "PmxComparisonError",
    "PmxFaceEditError",
    "PmxFrameEditError",
    "PmxInspectionError",
    "PmxFormatError",
    "PmxJointEditError",
    "PmxMaterialEditError",
    "PmxMorphEditError",
    "PmxPatchError",
    "PmxPlanError",
    "PmxPlanStaleError",
    "PmxQueryError",
    "PmxRigidBodyEditError",
    "PmxTransactionError",
    "PmxVertexEditError",
    "PmxWorkspaceError",
    "PmxValidationError",
    "UnsupportedPmxFeatureError",
    "PmxByteSpan",
    "PmxCursor",
    "BinaryPatch",
    "BinarySpan",
    "FieldPath",
    "PmxDocument",
    "PmxLimits",
    "DEFAULT_PMX_LIMITS",
    "JointType",
    "MorphMaterialOperation",
    "MorphPanel",
    "MorphType",
    "PmxIndexSize",
    "PmxTextEncoding",
    "RigidBodyPhysMode",
    "RigidBodyShape",
    "SoftBodyAeroModel",
    "SoftBodyFlags",
    "SoftBodyShape",
    "SphMode",
    "ToonSharing",
    "WeightMode",
    "PmxParseReport",
    "PmxParseResult",
    "PmxSectionReport",
    "PMX_20_REQUIRED_SECTIONS",
    "PMX_21_REQUIRED_SECTIONS",
    "PmxValidator",
    "validate_pmx_model",
    "PmxIndexLayout",
    "PmxWriter",
    "PmxEditTransaction",
    "PmxTransactionResult",
    "edit_pmx",
    "PmxInspectionError",
    "PmxQueryError",
    "PmxCapabilityError",
    "PmxPlanError",
    "PmxPlanStaleError",
    "PmxComparisonError",
    "PmxWorkspaceError",
    "PmxResourceRef",
    "PmxEvidence",
    "PmxDiagnostic",
    "PmxInputSnapshot",
    "PmxInspectionLimits",
    "PmxCapabilities",
    "PmxInspection",
    "PmxResourceCandidate",
    "PmxQueryResult",
    "PmxDependencyGraph",
    "PmxMorphState",
    "PmxMorphEvaluation",
    "PmxBakeResult",
    "PmxAssemblyResult",
    "PmxBoneBinding",
    "PmxCoordinateTransform",
    "PmxSurfaceFitConfig",
    "PmxResourcePolicy",
    "PmxRemovalPolicy",
    "PmxVariantSpec",
    "PmxVariantResult",
    "PmxVariantBuildResult",
    "PmxVariantBuilder",
    "PmxPartSelection",
    "PmxPartResult",
    "PmxComparison",
    "PmxBoneCandidate",
    "PmxBoneSuggestion",
    "PmxPlanApproval",
    "PmxOperationPlan",
    "PmxWorkspaceSnapshot",
    "PmxWorkspace",
    "get_pmx_capabilities",
    "inspect_pmx",
    "find_pmx_resources",
    "analyze_part",
    "extract_part",
    "explain_pmx_dependencies",
    "who_references",
    "evaluate_morph_state",
    "bake_morph_state",
    "bake_or_preserve",
    "bind_part_to_target",
    "fit_part_to_surface",
    "assemble_part",
    "preview_morph_state",
    "suggest_bone_bindings",
    "compare_pmx_models",
    "plan_pmx_operation",
    "apply_plan",
]


def __getattr__(name: str) -> object:
    """Lazily expose transactions and observation APIs without a model cycle."""
    if name in {"PmxEditTransaction", "PmxTransactionResult", "edit_pmx"}:
        from pypmxvmd.common.pmx.transaction import (
            PmxEditTransaction,
            PmxTransactionResult,
            edit_pmx,
        )

        return {
            "PmxEditTransaction": PmxEditTransaction,
            "PmxTransactionResult": PmxTransactionResult,
            "edit_pmx": edit_pmx,
        }[name]
    outfit_names = {
        "PmxBoneCandidate",
        "PmxBoneSuggestion",
        "PmxCapabilityError",
        "PmxCapabilities",
        "PmxComparison",
        "PmxComparisonError",
        "PmxDependencyGraph",
        "PmxDiagnostic",
        "PmxEvidence",
        "PmxInputSnapshot",
        "PmxInspection",
        "PmxInspectionError",
        "PmxInspectionLimits",
        "PmxMorphEvaluation",
        "PmxMorphState",
        "PmxBakeResult",
        "PmxAssemblyResult",
        "PmxBoneBinding",
        "PmxCoordinateTransform",
        "PmxSurfaceFitConfig",
        "PmxResourcePolicy",
        "PmxRemovalPolicy",
        "PmxVariantSpec",
        "PmxVariantResult",
        "PmxVariantBuildResult",
        "PmxVariantBuilder",
        "PmxOperationPlan",
        "PmxPartResult",
        "PmxPartSelection",
        "PmxPlanApproval",
        "PmxPlanError",
        "PmxPlanStaleError",
        "PmxQueryError",
        "PmxQueryResult",
        "PmxResourceCandidate",
        "PmxResourceRef",
        "PmxWorkspace",
        "PmxWorkspaceError",
        "PmxWorkspaceSnapshot",
        "analyze_part",
        "apply_plan",
        "compare_pmx_models",
        "evaluate_morph_state",
        "bake_morph_state",
        "bake_or_preserve",
        "bind_part_to_target",
        "fit_part_to_surface",
        "assemble_part",
        "explain_pmx_dependencies",
        "extract_part",
        "find_pmx_resources",
        "get_pmx_capabilities",
        "inspect_pmx",
        "plan_pmx_operation",
        "preview_morph_state",
        "suggest_bone_bindings",
        "who_references",
    }
    if name in outfit_names:
        from pypmxvmd.common.pmx import outfit

        return getattr(outfit, name)
    raise AttributeError(name)
