"""PMX-specific parsing contracts and diagnostics."""

from pypmxvmd.common.pmx.cursor import PmxByteSpan, PmxCursor
from pypmxvmd.common.pmx.document import BinaryPatch, BinarySpan, FieldPath, PmxDocument
from pypmxvmd.common.pmx.errors import (
    IncompletePmxError,
    IncompletePmxWriterError,
    PmxBoneEditError,
    PmxError,
    PmxFormatError,
    PmxJointEditError,
    PmxMaterialEditError,
    PmxPatchError,
    PmxRigidBodyEditError,
    PmxValidationError,
    UnsupportedPmxFeatureError,
)
from pypmxvmd.common.pmx.limits import DEFAULT_PMX_LIMITS, PmxLimits
from pypmxvmd.common.pmx.report import (
    PMX_20_REQUIRED_SECTIONS,
    PMX_21_REQUIRED_SECTIONS,
    PmxParseReport,
    PmxParseResult,
    PmxSectionReport,
)
from pypmxvmd.common.pmx.types import (
    JointType,
    MorphMaterialOperation,
    MorphPanel,
    MorphType,
    PmxIndexSize,
    PmxTextEncoding,
    RigidBodyPhysMode,
    RigidBodyShape,
    SoftBodyAeroModel,
    SoftBodyFlags,
    SoftBodyShape,
    SphMode,
    ToonSharing,
    WeightMode,
)
from pypmxvmd.common.pmx.validator import PmxValidator, validate_pmx_model
from pypmxvmd.common.pmx.writer import PmxIndexLayout, PmxWriter

__all__ = [
    "IncompletePmxError",
    "IncompletePmxWriterError",
    "PmxError",
    "PmxBoneEditError",
    "PmxFormatError",
    "PmxJointEditError",
    "PmxMaterialEditError",
    "PmxPatchError",
    "PmxRigidBodyEditError",
    "PmxValidationError",
    "UnsupportedPmxFeatureError",
    "PmxByteSpan",
    "PmxCursor",
    "BinaryPatch",
    "BinarySpan",
    "FieldPath",
    "PmxDocument",
    "PmxLimits",
    "DEFAULT_PMX_LIMITS",
    "JointType",
    "MorphMaterialOperation",
    "MorphPanel",
    "MorphType",
    "PmxIndexSize",
    "PmxTextEncoding",
    "RigidBodyPhysMode",
    "RigidBodyShape",
    "SoftBodyAeroModel",
    "SoftBodyFlags",
    "SoftBodyShape",
    "SphMode",
    "ToonSharing",
    "WeightMode",
    "PmxParseReport",
    "PmxParseResult",
    "PmxSectionReport",
    "PMX_20_REQUIRED_SECTIONS",
    "PMX_21_REQUIRED_SECTIONS",
    "PmxValidator",
    "validate_pmx_model",
    "PmxIndexLayout",
    "PmxWriter",
]
